import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LeftSidebarHome from "../../../components/layout/LeftSidebarHome";
import RightSidebarHome from "../../../components/layout/RightSidebarHome";
import MainContainer from "../../../components/layout/MainContainer";
import BottomBar from "../../../components/layout/BottomBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-purple-2 text-light-1`}>
          <main className="flex flex-row">
            <LeftSidebarHome />
            <MainContainer>
              {children}
            </MainContainer>
            <RightSidebarHome />
          </main>
          <BottomBar/>
        </body>
      </html>
    </ClerkProvider>
  );
}
